---
title: Rahul Thakoor
timezone: Asia/Muscat
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: Rahul Thakoor
description: A blog about technology, maker culture and more
picture: assets/images/profile.png
resume: false
resume-external: true
resume-url: https://google.com/?q=my+resume
url: https://rahul-thakoor.github.io
permalink: "/:title/"
disqus:
  shortname: rahulthakoor
  categories:
  - blog
  - project
facebook: rahul.thakoor
twitter: rahulthakoor
github: rahul-thakoor
email: rahul27@qq.com
authors:
  rahul:
    name: Rahul Thakoor
    bio: Rahul is always looking for new challenges and has too many interests to
      be listed in a few lines.
    external-image: false
    picture: assets/images/profile.png
width: normal
about: true
blog: true
read-time: true
show-tags: true
related: true
post-advance-links:
- blog
show-author: true
animation: true
gems:
- jekyll-seo-tag
- jekyll-gist
- jekyll-mentions
jekyll-mentions:
  base_url: https://twitter.com
